### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by EzioGreggio** [ZionDevelopers/spotify-ad-autocloser#1]
With the new update of spotify web the plug-in unfortunately doesn't work anymore.

**Comment by juliocoliveira** [comment]
OK, I'll test and fix it if is really broken, This may take a while, because ads take a time to show, some days it does not show at all.
Thanks for the report, I don't use spotify every day. I'm testing it now.

**Comment by juliocoliveira** [comment]
OK, I got the new ad, and really, wasn't working anymore, thanks for letting me know, it was fixed on the latest update.
I'll test it the new update on Firefox, and push it to the add-on stores after it, for Firefox it takes seconds, for google chrome it takes days, so be patient.

**Comment by EzioGreggio** [comment]
Ok no problem, thank you for trying to fix it

**Comment by juliocoliveira** [comment]
An update was pushed to add-on web stores, I didn't managed to test on firefox because I was not getting ads again, each ad should show up every 15 minutes, but for some reason I'm not getting any. Anyway, it should be working fine. The update is available already on Firefox if you are using it, On google chrome-based browsers probably only Monday. If you are using google chrome you can download the source-code and load an unpacked extension for now.

**Comment by EzioGreggio** [comment]
Awesome, thanks for the update!
